[package]
name = "cairo-lang-parser"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo parser."

[features]
fix_parser_tests = ["cairo-lang-utils/testing"]

[dependencies]
colored.workspace = true
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "0.1.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "0.1.0" }
itertools.workspace = true
log.workspace = true
salsa.workspace = true
smol_str.workspace = true
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "0.1.0" }
cairo-lang-syntax-codegen = { path = "../cairo-lang-syntax-codegen", version = "0.1.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "0.1.0" }

[dev-dependencies]
env_logger.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", version = "0.1.0" }
