[package]
name = "cairo-lang-parser"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo parser."

[dependencies]
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "~2.10.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.10.1" }
cairo-lang-primitive-token.workspace = true
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.10.1" }
cairo-lang-syntax-codegen = { path = "../cairo-lang-syntax-codegen", version = "~2.10.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.10.1" }
colored.workspace = true
itertools = { workspace = true, default-features = true }
num-bigint = { workspace = true, default-features = true }
num-traits = { workspace = true, default-features = true }
salsa.workspace = true
smol_str.workspace = true
unescaper.workspace = true

[dev-dependencies]
anstream = "0.6.18"
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
env_logger.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
indoc.workspace = true
