[package]
name = "cairo-lang-filesystem"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Virtual filesystem for the compiler."

[dependencies]
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.0.0-alpha.2" }
cairo-lang-debug = { path = "../cairo-lang-debug", version = "1.0.0-alpha.2" }
path-clean.workspace = true
salsa.workspace = true
smol_str.workspace = true

[dev-dependencies]
env_logger.workspace = true
test-log.workspace = true
