[package]
name = "cairo-lang-filesystem"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Virtual filesystem for the compiler."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1", features = ["serde"] }
||||||| 34923c147
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.1" }
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.3" }
>>>>>>> origin/dev-v2.4.3
path-clean.workspace = true
salsa.workspace = true
serde = { workspace = true, default-features = true }
smol_str.workspace = true

[dev-dependencies]
env_logger.workspace = true
serde_json.workspace = true
test-log.workspace = true

[package.metadata.cargo-machete]
ignored = ["cairo-lang-debug"]
