[package]
name = "cairo-lang-project"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo project specification. For example, crates and flags used for compilation."

[dependencies]
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.6.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.6.3" }
serde = { workspace = true, default-features = true }
smol_str.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
