[package]
name = "cairo-lang-project"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo project specification. For example, crates and flags used for compilation."

[dependencies]
<<<<<<< HEAD
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.9.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.9.3" }
||||||| 63dc720fc
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.9.2" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.9.2" }
=======
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.10.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.10.0" }
>>>>>>> origin/dev-v2.10.0
serde = { workspace = true, default-features = true }
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
