[package]
name = "cairo-lang-project"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo project specification. For example, crates and flags used for compilation."

[dependencies]
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.0.0-rc1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.0-rc1" }
serde.workspace = true
smol_str.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
indoc.workspace = true
test-log.workspace = true
