[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
defs = { path = "../defs" }
db_utils = { path = "../db_utils" }
env_logger.workspace = true
filesystem = { path = "../filesystem" }
lowering = { path = "../lowering" }
semantic = { path = "../semantic" }
sierra = { path = "../sierra" }
sierra_generator = { path = "../sierra_generator" }
syntax = { path = "../syntax" }
parser = { path = "../parser" }
project = { path = "../project" }
salsa.workspace = true
test_utils_macros = { path = "../test_utils_macros" }
thiserror.workspace = true


[dev-dependencies]
test-log.workspace = true

[[bin]]
name = "cairo-compile"
path = "src/cli.rs"
