[package]
name = "cairo-size-profiler"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Runner executable for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true
mimalloc = { workspace = true, optional = true }

cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.13.1" }
cairo-lang-defs = { path = "../../cairo-lang-defs", version = "~2.13.1" }
cairo-lang-diagnostics = { path = "../../cairo-lang-diagnostics", version = "~2.13.1" }
cairo-lang-executable = { path = "../../cairo-lang-executable", version = "~2.13.1" }
cairo-lang-executable-plugin = { path = "../../cairo-lang-executable-plugin", version = "~2.13.1" }
cairo-lang-filesystem = { path = "../../cairo-lang-filesystem", version = "~2.13.1" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "~2.13.1" }
cairo-lang-runnable-utils = { path = "../../cairo-lang-runnable-utils", version = "~2.13.1" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.13.1" }
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "~2.13.1" }
cairo-lang-sierra-generator = { path = "../../cairo-lang-sierra-generator", version = "~2.13.1" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "~2.13.1" }
cairo-lang-syntax = { path = "../../cairo-lang-syntax", version = "~2.13.1" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.13.1" }
itertools = { workspace = true, default-features = true }
salsa.workspace = true

[features]

mimalloc = ["dep:mimalloc"]
