[package]
name = "cairo-lang-diagnostics"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Diagnostic utilities."

[dependencies]
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.0.0-rc5" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.0-rc5" }
itertools.workspace = true
salsa.workspace = true

[dev-dependencies]
<<<<<<< HEAD
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros" }
=======
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros", version = "2.0.0-rc5" }
>>>>>>> v2.0.0-rc5
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
