[package]
name = "cairo-lang-diagnostics"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Diagnostic utilities."

[dependencies]
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.0.0-alpha.7" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.0.0-alpha.7" }
itertools.workspace = true
salsa.workspace = true

[dev-dependencies]
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros", version = "1.0.0-alpha.7" }
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
