[package]
name = "cairo-lang-diagnostics"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Diagnostic utilities."

[dependencies]
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.4.0-rc5" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.4.0-rc5" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.0-rc5" }
itertools.workspace = true

[dev-dependencies]
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
