[package]
name = "cairo-lang-diagnostics"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Diagnostic utilities."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.12.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.0", features = ["tracing"] }
||||||| c9743105f
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.12.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.0" }
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.12.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.1" }
>>>>>>> origin/dev-v2.12.1
itertools = { workspace = true, default-features = true }
salsa.workspace = true

[dev-dependencies]
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
indoc.workspace = true
pretty_assertions.workspace = true
tracing.workspace = true
