[package]
name = "semantic"
version.workspace = true
edition.workspace = true

[features]
testing = []

[dependencies]
db_utils = { path = "../db_utils" }
defs = { path = "../defs" }
debug = { path = "../debug" }
diagnostics = { path = "../diagnostics" }
diagnostics_proc_macros = { path = "../diagnostics_proc_macros" }
env_logger.workspace = true
filesystem = { path = "../filesystem" }
id-arena.workspace = true
itertools.workspace = true
parser = { path = "../parser" }
# TODO(spapini): Only in testing feature.
pretty_assertions.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
salsa.workspace = true
smol_str.workspace = true
syntax = { path = "../syntax" }
test_utils_macros = { path = "../test_utils_macros" }
utils = { path = "../utils" }

[dev-dependencies]
assert_matches.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
utils = { path = "../utils", features = ["testing"] }
