[profile.release]
overflow-checks = true     # Enable integer overflow checks.

[profile.release-with-debug]
inherits = "release"
debug = true

[workspace]
resolver = "2"
members = [
    "crates/cairo-lang-casm",
    "crates/cairo-lang-compiler",
    "crates/cairo-lang-debug",
    "crates/cairo-lang-defs",
    "crates/cairo-lang-diagnostics",
    "crates/cairo-lang-eq-solver",
    "crates/cairo-lang-filesystem",
    "crates/cairo-lang-formatter",
    "crates/cairo-lang-language-server",
    "crates/cairo-lang-lowering",
    "crates/cairo-lang-parser",
    "crates/cairo-lang-plugins",
    "crates/cairo-lang-proc-macros",
    "crates/cairo-lang-project",
    "crates/cairo-lang-runner",
    "crates/cairo-lang-semantic",
    "crates/cairo-lang-sierra",
    "crates/cairo-lang-sierra-ap-change",
    "crates/cairo-lang-sierra-gas",
    "crates/cairo-lang-sierra-generator",
    "crates/cairo-lang-sierra-to-casm",
    "crates/cairo-lang-sierra-type-size",
    "crates/cairo-lang-starknet",
    "crates/cairo-lang-syntax",
    "crates/cairo-lang-syntax-codegen",
    "crates/cairo-lang-test-plugin",
    "crates/cairo-lang-test-runner",
    "crates/cairo-lang-utils",
    "crates/bin/cairo-compile",
    "crates/bin/cairo-format",
    "crates/bin/cairo-language-server",
    "crates/bin/cairo-run",
    "crates/bin/cairo-test",
    "crates/bin/generate-syntax",
    "crates/bin/sierra-compile",
    "crates/bin/starknet-compile",
    "crates/bin/starknet-sierra-compile",
    "crates/bin/starknet-sierra-extract-code",
    "tests",
]

[workspace.package]
version = "2.3.1"
edition = "2021"
repository = "https://github.com/starkware-libs/cairo/"
license = "Apache-2.0"
license-file = "LICENSE"

[workspace.dependencies]
anyhow = "1.0.75"
ark-ff = "0.4.2"
ark-secp256k1 = "0.4.0"
ark-secp256r1 = "0.4.0"
ark-std = "0.4.0"
assert_matches = "1.5"
bimap = "0.6.3"
cairo-felt = "0.9.0"
cairo-vm = "0.9.0"
clap = { version = "4.4", features = ["derive"] }
colored = "2"
const-fnv1a-hash = "1.1.0"
const_format = "0.2.32"
convert_case = "0.6.0"
derivative = "2.2.0"
diffy = "0.3.0"
env_logger = "0.10.0"
genco = "0.17.8"
good_lp = { version = "1.7.0", features = ["minilp"], default-features = false }
id-arena = "2.2.1"
ignore = "0.4.20"
indent = "0.1.1"
indexmap = { version = "2.1.0", features = ["serde"] }
indoc = "2.0.4"
itertools = "0.11.0"
keccak = "0.1.4"
lalrpop-util = { version = "0.20.0", features = ["lexer"] }
log = "0.4"
lsp = { version = "0.94", package = "lsp-types" }
num-bigint = { version = "0.4", features = ["serde"] }
num-integer = "0.1"
num-traits = "0.2"
once_cell = "1.18.0"
parity-scale-codec = "3.6.5"
parity-scale-codec-derive = "3.6.5"
path-clean = "1.0.1"
pretty_assertions = "1.4.0"
proc-macro2 = "1.0"
quote = "1.0.33"
rayon = "1.8.0"
rstest = "0.18.2"
rust-analyzer-salsa = "0.17.0-pre.3"
scarb-metadata = "1"
schemars = { version = "0.8.15", features = ["preserve_order"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10.8"
smol_str = { version = "0.2.0", features = ["serde"] }
starknet-crypto = "0.6.1"
syn = { version = "2.0.39", features = ["full", "extra-traits"] }
test-case = "3.2.1"
test-case-macros = "3.2.1"
test-log = "0.2.13"
thiserror = "1.0.50"
time = { version = "0.3.30", features = [
    "formatting",
    "macros",
    "local-offset",
] }
tokio = { version = "1.33.0", features = ["full", "sync"] }
toml = "0.8.8"
tower-lsp = "0.20.0"
unescaper = "0.1.2"
xshell = "0.2.5"
