[workspace]

members = [
    "crates/cairo-lang-casm",
    "crates/cairo-lang-compiler",
    "crates/cairo-lang-debug",
    "crates/cairo-lang-defs",
    "crates/cairo-lang-diagnostics",
    "crates/cairo-lang-eq-solver",
    "crates/cairo-lang-filesystem",
    "crates/cairo-lang-formatter",
    "crates/cairo-lang-language-server",
    "crates/cairo-lang-lowering",
    "crates/cairo-lang-parser",
    "crates/cairo-lang-plugins",
    "crates/cairo-lang-proc-macros",
    "crates/cairo-lang-project",
    "crates/cairo-lang-runner",
    "crates/cairo-lang-semantic",
    "crates/cairo-lang-sierra",
    "crates/cairo-lang-sierra-ap-change",
    "crates/cairo-lang-sierra-gas",
    "crates/cairo-lang-sierra-generator",
    "crates/cairo-lang-sierra-to-casm",
    "crates/cairo-lang-starknet",
    "crates/cairo-lang-syntax",
    "crates/cairo-lang-syntax-codegen",
    "crates/cairo-lang-test-runner",
    "crates/cairo-lang-utils",
    "crates/bin/cairo-language-server",
    "crates/bin/cairo-compile",
    "crates/bin/cairo-format",
    "crates/bin/cairo-test",
    "crates/bin/cairo-run",
    "crates/bin/sierra-compile",
    "crates/bin/starknet-compile",
    "crates/bin/starknet-sierra-compile",
    "crates/bin/generate-syntax",
    "tests",
]

[workspace.package]
version = "2.0.0-rc1"
edition = "2021"
repository = "https://github.com/starkware-libs/cairo/"
license = "Apache-2.0"
license-file = "LICENSE"

[workspace.dependencies]
anyhow = "1.0.66"
ark-ff = "0.4.0-alpha.7"
ark-secp256k1 = "0.4.0"
ark-secp256r1 = "0.4.0"
ark-std = "0.3.0"
assert_matches = "1.5"
bimap = "0.6.2"
cairo-felt = "0.5.1"
cairo-vm = "0.5.1"
clap = { version = "4.0", features = ["derive"] }
colored = "2"
const-fnv1a-hash = "1.1.0"
convert_case = "0.6.0"
derivative = "2.2.0"
diffy = "0.3.0"
env_logger = "0.9.3"
genco = "0.17.0"
good_lp = { version = "1.3.2", features = ["minilp"], default-features = false }
id-arena = "2.2.1"
ignore = "0.4.20"
indexmap = { version = "1.9.1", features = ["serde"] }
indoc = "2.0.1"
itertools = "0.10.3"
keccak = "0.1.3"
lalrpop-util = { version = "0.19.9", features = ["lexer"] }
log = "0.4"
lsp = { version = "0.93", package = "lsp-types" }
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
once_cell = "1.17.1"
parity-scale-codec = "3.5.0"
parity-scale-codec-derive = "3.1.4"
path-clean = "0.1.0"
pretty_assertions = "1.2.1"
proc-macro2 = "1.0"
quote = "1.0.21"
rayon = "1.7.0"
rstest = "0.16.0"
salsa = "0.17.0-pre.2"
scarb-metadata = "1.3.0"
schemars = { version = "0.8.12", features = ["preserve_order"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10.6"
smol_str = { version = "0.2.0", features = ["serde"] }
syn = { version = "1.0.99", features = ["full", "extra-traits"] }
test-case = "2.2.2"
test-case-macros = "2.2.2"
test-log = "0.2.11"
thiserror = "1.0.32"
time = { version = "0.3.20", features = [
    "formatting",
    "macros",
    "local-offset",
] }
tokio = { version = "1.18.2", features = ["full", "sync"] }
toml = "0.4.2"
tower-lsp = "0.17.0"
unescaper = "0.1.1"
xshell = "0.2.2"
