edition = "2024"
max_width = 100
newline_style = "unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

# Unstable features below
comment_width = 100
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
style_edition = "2024"
unstable_features = true
wrap_comments = true

# To use these settings in vscode, add the following line to your settings:
#     "rust-analyzer.rustfmt.overrideCommand": [
#         "rustup",
#         "run",
#         "nightly-2025-11-02",
#         "--",
#         "rustfmt",
#         "--edition",
#         "2024",
#         "--"
#     ]
# and run "rustup toolchain install nightly-2025-11-02".
