edition = "2018"
newline_style = "unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
max_width = 100

# Unstable features below
unstable_features = true
version = "Two"
comment_width = 100
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# To use these settings in vscode, add the following line to your settings:
#     "rust-analyzer.rustfmt.overrideCommand": [
#         "rustup",
#         "run",
#         "nightly-2022-07-27",
#         "--",
#         "rustfmt",
#         "--edition",
#         "2018",
#         "--"
#     ]
# and run "rustup toolchain install nightly-2022-07-27".
