[package]
name = "cairo-proc-macros"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Procedural macros."

[lib]
proc-macro = true

[package.metadata.cargo-udeps.ignore]
normal = ["cairo-debug"]

[dependencies]
# This is used only for docs.
cairo-debug = { path = "../cairo-debug" }
quote.workspace = true
syn.workspace = true
