[package]
name = "cairo-lang-plugins"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo core plugin implementations."

[features]
testing = []

[dependencies]
cairo-lang-defs = { path = "../cairo-lang-defs", version = "~2.10.1" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "~2.10.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.10.1" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "~2.10.1" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.10.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.10.1" }
indent.workspace = true
indoc.workspace = true
itertools = { workspace = true, default-features = true }
salsa.workspace = true
smol_str.workspace = true

[dev-dependencies]
cairo-lang-debug = { path = "../cairo-lang-debug" }
cairo-lang-parser = { path = "../cairo-lang-parser" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
env_logger.workspace = true
indoc.workspace = true
serde_json.workspace = true
test-log.workspace = true
