[package]
name = "cairo-lang-runner"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Basic cairo runner."

[dependencies]
ark-ff.workspace = true
ark-secp256k1.workspace = true
ark-secp256r1.workspace = true

cairo-lang-casm = { path = "../cairo-lang-casm", version = "~2.10.1" }
cairo-lang-lowering = { path = "../cairo-lang-lowering", version = "~2.10.1" }
cairo-lang-runnable-utils = { path = "../cairo-lang-runnable-utils", version = "~2.10.1" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "~2.10.1" }
cairo-lang-sierra-generator = { path = "../cairo-lang-sierra-generator", version = "~2.10.1" }
cairo-lang-sierra-to-casm = { path = "../cairo-lang-sierra-to-casm", version = "~2.10.1" }
cairo-lang-starknet = { path = "../cairo-lang-starknet", version = "~2.10.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.10.1" }
cairo-vm.workspace = true
itertools = { workspace = true, default-features = true }
keccak.workspace = true
num-bigint = { workspace = true, default-features = true }
num-integer.workspace = true
num-traits = { workspace = true, default-features = true }
rand.workspace = true
sha2.workspace = true
smol_str.workspace = true
starknet-types-core.workspace = true
thiserror.workspace = true

[dev-dependencies]
cairo-lang-compiler = { path = "../cairo-lang-compiler" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", features = ["testing"] }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
env_logger.workspace = true
indoc.workspace = true
test-case.workspace = true
test-log.workspace = true

[package.metadata.cargo-machete]
ignored = ["ark-secp256k1", "ark-secp256r1"]
