[package]
name = "cairo-lang-runner"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Basic cairo runner."

[dependencies]
anyhow.workspace = true
ark-ff.workspace = true
ark-secp256k1.workspace = true
ark-std.workspace = true
cairo-felt.workspace = true
cairo-lang-casm = { path = "../cairo-lang-casm", version = "1.1.0-rc0" }
cairo-lang-compiler = { path = "../cairo-lang-compiler", version = "1.1.0-rc0" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "1.1.0-rc0" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "1.1.0-rc0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.1.0-rc0" }
cairo-lang-lowering = { path = "../cairo-lang-lowering", version = "1.1.0-rc0" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "1.1.0-rc0" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "1.1.0-rc0" }
cairo-lang-sierra-ap-change = { path = "../cairo-lang-sierra-ap-change", version = "1.1.0-rc0" }
cairo-lang-sierra-gas = { path = "../cairo-lang-sierra-gas", version = "1.1.0-rc0" }
cairo-lang-sierra-generator = { path = "../cairo-lang-sierra-generator", version = "1.1.0-rc0" }
cairo-lang-sierra-to-casm = { path = "../cairo-lang-sierra-to-casm", version = "1.1.0-rc0" }
cairo-lang-starknet = { path = "../cairo-lang-starknet", version = "1.1.0-rc0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.1.0-rc0" }
cairo-vm.workspace = true
clap.workspace = true
itertools.workspace = true
keccak.workspace = true
num-bigint.workspace = true
num-integer.workspace = true
num-traits.workspace = true
salsa.workspace = true
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
test-case.workspace = true

[[bin]]
name = "cairo-run"
path = "src/cli.rs"
