[package]
name = "starknet-sierra-extract-code"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for printing Starknet Sierra json included code"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "2.3.0-rc0" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.3.0-rc0" }
