[package]
name = "starknet-sierra-extract-code"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for printing Starknet Sierra json included code"
publish = false

[dependencies]
anyhow.workspace = true
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.12.2" }
clap.workspace = true
serde_json.workspace = true
