[package]
name = "starknet-sierra-extract-code"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for printing Starknet Sierra json included code"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
<<<<<<< HEAD
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.5.0-dev.0" }
||||||| 1c02dc554
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.4.1" }
=======
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.4.4" }
>>>>>>> origin/main
