[package]
name = "casm"
version.workspace = true
edition.workspace = true

[dependencies]
cairo-rs = { git = "https://github.com/lambdaclass/cairo-rs", rev="3a2dead" }
env_logger.workspace = true
thiserror.workspace = true
num-bigint.workspace = true
test_utils_macros = { path = "../test_utils_macros" }
utils = { path = "../utils" }

[dev-dependencies]
indoc.workspace = true
itertools.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
