[package]
name = "casm"
version.workspace = true
edition.workspace = true

[dependencies]
cairo-rs.workspace = true
thiserror.workspace = true
num-bigint.workspace = true
utils = { path = "../utils" }
indoc.workspace = true

[dev-dependencies]
env_logger.workspace = true
itertools.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
