[package]
name = "cairo-language-server"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Language server executable for the Cairo programming language"

[dependencies]
cairo-lang-language-server = { path = "../../cairo-lang-language-server", version = "~2.6.3" }
