[package]
name = "cairo-language-server"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Language server executable for the Cairo programming language"

[dependencies]
tokio.workspace = true
log.workspace = true

cairo-lang-language-server = { path = "../../cairo-lang-language-server", version = "2.0.0-rc2" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.0.0-rc2", features = [
    "env_logger",
] }
