[package]
name = "cairo_python_bindings"
version = "1.0.0-alpha.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
cairo-lang-compiler = { path = "../cairo-lang-compiler" }
cairo-lang-runner = { path = "../cairo-lang-runner" }
cairo-lang-sierra-to-casm = { path = "../cairo-lang-sierra-to-casm" }
cairo-lang-starknet = { path = "../cairo-lang-starknet" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "1.0.0-alpha.2" }
cairo-lang-plugins = { path = "../cairo-lang-plugins", version = "1.0.0-alpha.2" }
cairo-lang-sierra-generator = { path = "../cairo-lang-sierra-generator", version = "1.0.0-alpha.2" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "1.0.0-alpha.2" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "1.0.0-alpha.2" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.0.0-alpha.2" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.0.0-alpha.2" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "1.0.0-alpha.2" }
cairo-lang-protostar = { path = "../cairo-lang-protostar" }
cairo-lang-debug = { path = "../cairo-lang-debug" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "1.0.0-alpha.2" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[lib]
name = "cairo_python_bindings"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.10.1"
features = ["extension-module"]