[package]
name = "sierra"
version = "0.1.0"
edition = "2021"
build = "src/build.rs" # LALRPOP preprocessing

[build-dependencies]
lalrpop = "0.19.8"
regex = "1"

[dev-dependencies]
assert_matches = "1.5"
indoc = "1.0.7"
test-case = "2.2.1"

[dependencies]
array-init = "2.0.1"
const-fnv1a-hash = "1.1.0"
itertools = "0.10.3"
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
thiserror = "1.0.32"
salsa = "0.16.1"
smol_str = "0.1.23"
