[package]
name = "cairo-test"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Test runner for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true

cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "2.0.0-rc3" }
