[package]
name = "cairo-test"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Test runner for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde = { workspace = true, default-features = true }

<<<<<<< HEAD
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.9.3" }
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "~2.9.3" }
||||||| 63dc720fc
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.9.2" }
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "~2.9.2" }
=======
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.10.0" }
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "~2.10.0" }
>>>>>>> origin/dev-v2.10.0
