[package]
name = "cairo-test"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Test runner for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true

<<<<<<< HEAD
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "2.5.0-dev.0" }
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "2.5.0-dev.0" }
||||||| 1c02dc554
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "2.4.1" }
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "2.4.1" }
=======
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "2.4.4" }
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "2.4.4" }
>>>>>>> origin/main
