[package]
name = "cairo-lang-sierra-type-size"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra type sizes computation."

[dependencies]
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.5.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.5.4" }
