[package]
name = "cairo-lang-sierra-gas"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra gas computation."

[dependencies]
itertools.workspace = true
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "1.0.0-alpha.5" }
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "1.0.0-alpha.5" }
thiserror.workspace = true
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.0.0-alpha.5" }

[dev-dependencies]
env_logger.workspace = true
indoc.workspace = true
test-case.workspace = true
test-log.workspace = true
pretty_assertions.workspace = true
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", version = "1.0.0-alpha.5" }
