[package]
name = "languageserver"
version.workspace = true
edition.workspace = true

[[bin]]
name = "languageserver"

[dependencies]
db_utils = { path = "../db_utils" }
defs = { path = "../defs" }
debug = { path = "../debug" }
diagnostics = { path = "../diagnostics" }
env_logger.workspace = true
lowering = { path = "../lowering" }
semantic = { path = "../semantic" }
formatter = { path = "../formatter" }
parser = { path = "../parser" }
project = { path = "../project" }
syntax = { path = "../syntax" }
filesystem = { path = "../filesystem" }
tokio.workspace = true
tower-lsp.workspace = true
lsp.workspace = true
serde_json.workspace = true
salsa.workspace = true
test_utils_macros = { path = "../test_utils_macros" }
utils = { path = "../utils" }

[dev-dependencies]
test-log.workspace = true

