[package]
name = "cairo-run"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Runner executable for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true

<<<<<<< HEAD
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.9.3" }
cairo-lang-diagnostics = { path = "../../cairo-lang-diagnostics", version = "~2.9.3" }
cairo-lang-filesystem = { path = "../../cairo-lang-filesystem", version = "~2.9.3" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.9.3" }
cairo-lang-sierra-generator = { path = "../../cairo-lang-sierra-generator", version = "~2.9.3" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "~2.9.3" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.9.3" }
||||||| 63dc720fc
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.9.2" }
cairo-lang-diagnostics = { path = "../../cairo-lang-diagnostics", version = "~2.9.2" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.9.2" }
cairo-lang-sierra-generator = { path = "../../cairo-lang-sierra-generator", version = "~2.9.2" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "~2.9.2" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.9.2" }
=======
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.10.0" }
cairo-lang-diagnostics = { path = "../../cairo-lang-diagnostics", version = "~2.10.0" }
cairo-lang-filesystem = { path = "../../cairo-lang-filesystem", version = "~2.10.0" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.10.0" }
cairo-lang-sierra-generator = { path = "../../cairo-lang-sierra-generator", version = "~2.10.0" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "~2.10.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.10.0" }
>>>>>>> origin/dev-v2.10.0
