[package]
name = "get-lowering"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for the Cairo programming language with the StarkNet plugin."

[dependencies]
anyhow.workspace = true
clap.workspace = true
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "2.5.0" }
cairo-lang-defs = { path = "../../cairo-lang-defs", version = "2.5.0" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "2.5.0" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.5.0" }
cairo-lang-semantic = { path = "../../cairo-lang-semantic", version = "2.5.0" }
