[package]
name = "get-lowering"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for the Cairo programming language with the Starknet plugin."
publish = false

[dependencies]
anyhow.workspace = true
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "2.14.0" }
cairo-lang-debug = { path = "../../cairo-lang-debug", version = "2.14.0" }
cairo-lang-defs = { path = "../../cairo-lang-defs", version = "2.14.0" }
cairo-lang-executable-plugin = { path = "../../cairo-lang-executable-plugin", version = "~2.14.0" }
cairo-lang-filesystem = { path = "../../cairo-lang-filesystem", version = "~2.14.0" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "~2.14.0" }
cairo-lang-semantic = { path = "../../cairo-lang-semantic", version = "~2.14.0" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "~2.14.0" }
cairo-lang-test-plugin = { path = "../../cairo-lang-test-plugin", version = "~2.14.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.14.0" }
clap.workspace = true
convert_case.workspace = true
itertools.workspace = true
mimalloc = { workspace = true, optional = true }
salsa.workspace = true

[features]

mimalloc = ["dep:mimalloc"]
