[package]
name = "cairo-test-utils"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Utilities for writing tests in the Cairo compiler project."

[dependencies]
cairo-utils = { path = "../cairo-utils" }
log.workspace = true
env_logger.workspace = true
pretty_assertions.workspace = true

[dev-dependencies]
test-log.workspace = true
