[package]
name = "sierra_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
defs = {path = "../defs"}
salsa = "0.16.1"
semantic = { path = "../semantic" }
sierra = { path = "../sierra" }
smol_str = "0.1.23"

[dev_dependencies]
filesystem = { path = "../filesystem" }
parser = { path = "../parser" }
pretty_assertions = "1.2.1"
syntax = { path = "../syntax" }
