[package]
name = "cairo-lang-casm"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo assembly encoding."

[dependencies]
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.0-rc2" }
indoc.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
parity-scale-codec.workspace = true
parity-scale-codec-derive.workspace = true
schemars = { workspace = true, features = ["preserve_order"] }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
env_logger.workspace = true
itertools.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
