[package]
name = "cairo-lang-debug"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Debug utilities for query objects."

[dev-dependencies]
cairo-lang-utils = { path = "../cairo-lang-utils" }
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros" }
env_logger.workspace = true
salsa.workspace = true
test-log.workspace = true
