[package]
name = "cairo-lang-semantic"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo semantic model."

[features]
testing = ["dep:cairo-lang-test-utils"]

[dependencies]
cairo-lang-debug = { path = "../cairo-lang-debug", version = "2.3.1" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "2.3.1" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "2.3.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.3.1" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "2.3.1" }
cairo-lang-plugins = { path = "../cairo-lang-plugins", version = "2.3.1" }
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros", version = "2.3.1" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "2.3.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.3.1" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", optional = true, features = ["testing"], version = "2.3.1" }
id-arena.workspace = true
indoc.workspace = true
itertools.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
once_cell.workspace = true
rust-analyzer-salsa.workspace = true
smol_str.workspace = true

[dev-dependencies]
cairo-lang-plugins = { path = "../cairo-lang-plugins" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
env_logger.workspace = true
log.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
