[package]
name = "cairo-lang-semantic"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo semantic model."

[features]
testing = []

[dependencies]
cairo-lang-debug = { path = "../cairo-lang-debug", version = "1.0.0-alpha.7" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "1.0.0-alpha.7" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "1.0.0-alpha.7" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "1.0.0-alpha.7" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "1.0.0-alpha.7" }
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros", version = "1.0.0-alpha.7" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "1.0.0-alpha.7" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.0.0-alpha.7" }
id-arena.workspace = true
itertools.workspace = true
log.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
salsa.workspace = true
smol_str.workspace = true

[dev-dependencies]
assert_matches.workspace = true
cairo-lang-plugins = { path = "../cairo-lang-plugins" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils" }
env_logger.workspace = true
indoc.workspace = true
log.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
