[package]
name = "cairo-lang-semantic"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo semantic model."

[features]
testing = ["dep:cairo-lang-test-utils", "dep:toml"]

[dependencies]
bincode.workspace = true
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.14.0" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "~2.14.0" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "~2.14.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.14.0" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "~2.14.0" }
cairo-lang-plugins = { path = "../cairo-lang-plugins", version = "~2.14.0" }
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros", version = "~2.14.0" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.14.0" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", version = "~2.14.0", optional = true, features = [
  "testing",
] }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.14.0", features = ["tracing"] }
id-arena.workspace = true
indoc.workspace = true
itertools = { workspace = true, default-features = true }
num-bigint = { workspace = true, default-features = true }
num-traits = { workspace = true, default-features = true }
salsa.workspace = true
serde.workspace = true
sha3.workspace = true
starknet-types-core.workspace = true
toml = { workspace = true, optional = true }

[dev-dependencies]
cairo-lang-plugins = { path = "../cairo-lang-plugins" }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
log.workspace = true
pretty_assertions.workspace = true
toml.workspace = true
tracing.workspace = true
