[package]
name = "cairo-lang-language-server"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo language server."

[dependencies]
anyhow.workspace = true
cairo-lang-compiler = { path = "../cairo-lang-compiler", version = "2.3.1" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "2.3.1" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "2.3.1" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "2.3.1" }
cairo-lang-formatter = { path = "../cairo-lang-formatter", version = "2.3.1" }
cairo-lang-lowering = { path = "../cairo-lang-lowering", version = "2.3.1" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "2.3.1" }
cairo-lang-project = { path = "../cairo-lang-project", version = "2.3.1" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "2.3.1" }
cairo-lang-starknet = { path = "../cairo-lang-starknet", version = "2.3.1" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "2.3.1" }
cairo-lang-test-plugin = { path = "../cairo-lang-test-plugin", version = "2.3.1" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.3.1" }
log.workspace = true
lsp.workspace = true
rust-analyzer-salsa.workspace = true
scarb-metadata.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-lsp.workspace = true

[dev-dependencies]
