[package]
name = "cairo-prove"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Executable for creating provable runnables and running such runnables for the Cairo programming language"

[dependencies]
anyhow.workspace = true
bincode = { version = "2.0.0-rc.3" }
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.8.5" }
cairo-lang-runnable = { path = "../../cairo-lang-runnable", version = "~2.8.5" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.8.5" }
cairo-vm =  { workspace = true, features = ["clap"] }
clap.workspace = true
num-bigint.workspace = true
serde_json.workspace = true
