[package]
name = "starknet"
version.workspace = true
edition.workspace = true

[dependencies]
defs = { path = "../defs" }
semantic = { path = "../semantic" }
serde.workspace = true
serde_json.workspace = true
syntax = { path = "../syntax" }
thiserror.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
semantic = { path = "../semantic", features = ["testing"] }
utils = { path = "../utils" }
