[package]
name = "starknet"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
compiler = { path = "../compiler" }
defs = { path = "../defs" }
itertools.workspace = true
semantic = { path = "../semantic" }
serde.workspace = true
serde_json.workspace = true
sierra = { path = "../sierra" }
sierra_generator = { path = "../sierra_generator" }
syntax = { path = "../syntax" }
sierra_gas = { path = "../sierra_gas" }
sierra_to_casm = { path = "../sierra_to_casm" }
thiserror.workspace = true
num-bigint.workspace = true
num-traits.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
semantic = { path = "../semantic", features = ["testing"] }
utils = { path = "../utils" }

[[bin]]
name = "starknet-compile"
path = "src/cli.rs"

[[bin]]
name = "starknet-sierra-compile"
path = "src/starknet_sierra_compile.rs"
