[package]
name = "cairo-lang-sierra-ap-change"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra AP change computation."

[dependencies]
cairo-lang-eq-solver = { path = "../cairo-lang-eq-solver", version = "2.0.0-rc0" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.0.0-rc0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.0.0-rc0" }
itertools.workspace = true
thiserror.workspace = true

[dev-dependencies]
env_logger.workspace = true
indoc.workspace = true
test-case.workspace = true
test-log.workspace = true
