[package]
name = "cairo-lang-sierra-ap-change"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra AP change computation."

[dependencies]
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "2.4.0-rc0" }
cairo-lang-sierra-type-size = { path = "../cairo-lang-sierra-type-size", version = "2.4.0-rc0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.4.0-rc0" }
itertools.workspace = true
thiserror.workspace = true

[dev-dependencies]
env_logger.workspace = true
