[package]
name = "cairo-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo compiler executable for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true
log.workspace = true

cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.10.1" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "~2.10.1" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.10.1", features = [
    "env_logger",
] }
