[package]
name = "starknet-sierra-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for the Sierra intemediate representation with StarkNet extensions"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "2.1.0-rc0", default-features = false }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "2.1.0-rc0", default-features = false }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "2.1.0-rc0", default-features = false }
cairo-lang-casm-contract-class = { path = "../../cairo-lang-casm-contract-class", version = "2.1.0-rc0", default-features = false, features = [
    "serde",
] }
