[package]
name = "starknet-sierra-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for the Sierra intermediate representation with Starknet extensions"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde = { workspace = true, default-features = true }
serde_json.workspace = true

<<<<<<< HEAD
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "~2.12.0" }
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.12.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.0", features = ["serde"] }
||||||| c9743105f
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "~2.12.0" }
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.12.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.0", features = [
    "serde",
] }
=======
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "~2.12.1" }
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.12.1" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.1", features = [
    "serde",
] }
>>>>>>> origin/dev-v2.12.1
