[package]
name = "starknet-sierra-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for the Sierra intemediate representation with StarkNet extensions"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde = { workspace = true, default-features = true }
serde_json.workspace = true

cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "~2.6.3" }
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.6.3" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.6.3", features = ["serde"] }
