[package]
name = "cairo-lang-sierra"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra representation."
build = "src/build.rs" # LALRPOP preprocessing

[build-dependencies]
lalrpop = "0.20.0"
regex = "1"

[dependencies]
anyhow.workspace = true
cairo-lang-utils = { path = "../cairo-lang-utils", version = "2.3.1" }
const-fnv1a-hash.workspace = true
convert_case.workspace = true
derivative.workspace = true
itertools.workspace = true
lalrpop-util.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
rust-analyzer-salsa.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
smol_str.workspace = true
thiserror.workspace = true

[dev-dependencies]
bimap.workspace = true
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
env_logger.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
