[package]
name = "cairo-runner"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Basic cairo runner."

[dependencies]
anyhow.workspace = true
cairo-vm.workspace = true
clap.workspace = true
cairo-compiler = { path = "../cairo-compiler" }
cairo-casm = { path = "../cairo-casm" }
cairo-diagnostics = { path = "../cairo-diagnostics" }
num-bigint.workspace = true
cairo-sierra = { path = "../cairo-sierra" }
cairo-sierra-ap-change = { path = "../cairo-sierra-ap-change" }
cairo-sierra-gas = { path = "../cairo-sierra-gas" }
cairo-sierra-generator = { path = "../cairo-sierra-generator" }
cairo-sierra-to-casm = { path = "../cairo-sierra-to-casm" }
cairo-utils = { path = "../cairo-utils" }
itertools.workspace = true
salsa.workspace = true
thiserror.workspace = true

[[bin]]
name = "cairo-run"
path = "src/cli.rs"
