[package]
name = "formatter"
version.workspace = true
edition.workspace = true

[[bin]]
name = "formatter_cli"
path = "src/bin/cli.rs"

[dependencies]
clap.workspace = true
colored.workspace = true
diffy.workspace = true
filesystem = { path = "../filesystem" }
itertools.workspace = true
parser = { path = "../parser" }
salsa.workspace = true
smol_str.workspace = true
syntax = { path = "../syntax" }

[dev-dependencies]
pretty_assertions.workspace = true
test-case.workspace = true
test-log.workspace = true
