[package]
name = "syntax"
version.workspace = true
edition.workspace = true

[dependencies]
db_utils = { path = "../db_utils" }
debug = { path = "../debug" }
filesystem = { path = "../filesystem" }
salsa.workspace = true
smol_str.workspace = true
utils = { path = "../utils" }

[dev-dependencies]
env_logger.workspace = true
pretty_assertions.workspace = true
test-log.workspace = true
