[package]
name = "cairo-lang-proc-macros"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Procedural macros."

[lib]
proc-macro = true

[package.metadata.cargo-machete]
ignored = ["cairo-lang-debug"]

[package.metadata.cargo-udeps.ignore]
normal = ["cairo-lang-debug"]

[dependencies]
# This is used only for docs.
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.14.0" }
quote.workspace = true
salsa.workspace = true
syn.workspace = true

[dev-dependencies]
expect-test = "1.5.1"
