[crate_roots]
core = "src"

[config.global]
edition = "2024_07"
version = "2.13.1"

[config.global.experimental_features]
associated_item_constraints = true
coupons = true
negative_impls = true
user_defined_inline_macros = true
