[crate_roots]
core = "src"

[config.global]
version = "2.12.0-dev.1"
edition = "2024_07"

[config.global.experimental_features]
negative_impls = true
associated_item_constraints = true
coupons = true
