[package]
name = "core"
version = "2.4.0-rc4"
edition = "2023_10"

# NOTE: This is non-public, unstable Scarb's field, which instructs resolver that this package does not
#   depend on `core`, which is only true for this particular package. Nobody else should use it.
no-core = true
