[package]
name = "core"
<<<<<<< HEAD
version = "2.7.0-rc.0"
edition = "2023_11"
||||||| cd8cb4d06
version = "2.6.4"
edition = "2023_11"
=======
version = "2.6.4"
edition = "2024_07"
>>>>>>> origin/main
experimental-features = ["coupons", "negative_impls"]

# NOTE: This is non-public, unstable Scarb's field, which instructs resolver that this package does not
#   depend on `core`, which is only true for this particular package. Nobody else should use it.
no-core = true

[dev-dependencies]
cairo_test = "2.7.0-rc.0"
