[package]
name = "core"
<<<<<<< HEAD
version = "2.4.3"
edition = "2023_11"
||||||| 6f359c1c6
version = "2.4.3"
edition = "2023_10"
=======
version = "2.4.4"
edition = "2023_10"
>>>>>>> origin/dev-v2.4.4

# NOTE: This is non-public, unstable Scarb's field, which instructs resolver that this package does not
#   depend on `core`, which is only true for this particular package. Nobody else should use it.
no-core = true
