[package]
name = "cairo-lang-syntax-codegen"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo syntax code generation."

[package.metadata.cargo-udeps.ignore]
normal = ["cairo-lang-syntax"]

[dependencies]
cairo-lang-utils = { path = "../cairo-lang-utils", version = "1.0.0-alpha.7" }
genco.workspace = true
log.workspace = true
xshell.workspace = true

[dev-dependencies]
env_logger.workspace = true
test-log.workspace = true

[[bin]]
name = "generate-syntax"
path = "src/generate_syntax.rs"
