[package]
name = "cairo-lang-syntax-codegen"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo syntax code generation."

[package.metadata.cargo-udeps.ignore]
normal = ["cairo-lang-syntax"]

[dependencies]
genco.workspace = true
xshell.workspace = true

[dev-dependencies]
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.13.0", features = ["tracing"] }
tracing.workspace = true
