[package]
name = "cairo-lang-test-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo test compilation plugin."

[dependencies]
anyhow.workspace = true
<<<<<<< HEAD
cairo-lang-compiler = { path = "../cairo-lang-compiler", version = "~2.9.2" }
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.9.2" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "~2.9.2" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.9.2" }
cairo-lang-lowering = { path = "../cairo-lang-lowering", version = "~2.9.2" }
cairo-lang-parser = { path = "../cairo-lang-parser", version = "~2.9.2" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "~2.9.2" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "~2.9.2" }
cairo-lang-sierra-generator = { path = "../cairo-lang-sierra-generator", version = "~2.9.2" }
cairo-lang-starknet = { path = "../cairo-lang-starknet", version = "~2.9.2" }
cairo-lang-starknet-classes = { path = "../cairo-lang-starknet-classes", version = "~2.9.2" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.9.2" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.9.2" }
=======
cairo-lang-compiler = { path = "../cairo-lang-compiler", version = "~2.11.4" }
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.11.4" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "~2.11.4" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.11.4" }
cairo-lang-lowering = { path = "../cairo-lang-lowering", version = "~2.11.4" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "~2.11.4" }
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "~2.11.4" }
cairo-lang-sierra-generator = { path = "../cairo-lang-sierra-generator", version = "~2.11.4" }
cairo-lang-starknet = { path = "../cairo-lang-starknet", version = "~2.11.4" }
cairo-lang-starknet-classes = { path = "../cairo-lang-starknet-classes", version = "~2.11.4" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.11.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.11.4" }
>>>>>>> 89e5551c2ef3a45da6ee0b9601a7abe9097c419c
indoc.workspace = true
itertools = { workspace = true, default-features = true }
num-bigint = { workspace = true, default-features = true }
num-traits = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true }
starknet-types-core.workspace = true
