[package]
name = "starknet-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for the Cairo programming language with the Starknet plugin."

[dependencies]
anyhow.workspace = true
clap.workspace = true

cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.10.1" }
cairo-lang-starknet = { path = "../../cairo-lang-starknet", version = "~2.10.1" }
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.10.1" }
