name: Crate Artifacts
on: workflow_dispatch
jobs:
  create_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install musl tools.
        run: sudo apt-get install -y musl-tools
      - name: Build in unknown linux
        run: ./scripts/release_tar.sh x86_64-unknown-linux-musl
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl.tar.gz
